In [2]:
import numpy as np

Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0) 

In [22]:
Z = np.zeros(shape=(8,8))
indici = [[i,j]for i in range(8) for j in range (8) if (i+j)%2==1]  #dove bisogna mettere 1, x+y è dispari
indici = np.array(indici)
#indici.T #scambia righe con colonne
#indici.T[0] array x, indici.t[1] array y
Z[indici.T[0],indici.T[1]] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


 Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [24]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
cont1 = 0
cont2 = 4
lista = []
for _ in range (11):
    lista.append(Z[cont1:cont2]) 
    cont1 += 1
    cont2 += 1
R = np.array(lista)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [ ]:
lista = []
for _ in range(15):
    lista.append(np.random.normal(170, 20, 1))
A = np.array(lista)
#print(lista)

altezze = np.array([180,171,182,175,171,177,175,179,174,185,185,190,176])
media = np.average(altezze) #average da la media 
        #media = 1/n(x1+x2+...+xn)
media  #m2 = 1/n(x1^2+x2^2+...+xn^2) 
       #deviazione standard = sqrt(m2-m^2)
    
dev_std = np.std(altezze)
dev_std #deviazione standard


#ammazza_pc: a = np.count_nonzero(np.random.normal(78.46,5.52,2000000000)>220)
a

Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [3]:
Z = np.ones((10,10))

for i in range (10//2-1,-1,-1):
    Z[i,:] = i+1
    Z[10-i-1,:] = i+1
    Z[:,i] = i+1
    Z[:,10-i-1] = i+1
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 2. 2. 2. 1.]
 [1. 2. 3. 3. 3. 3. 3. 3. 2. 1.]
 [1. 2. 3. 4. 4. 4. 4. 3. 2. 1.]
 [1. 2. 3. 4. 5. 5. 4. 3. 2. 1.]
 [1. 2. 3. 4. 5. 5. 4. 3. 2. 1.]
 [1. 2. 3. 4. 4. 4. 4. 3. 2. 1.]
 [1. 2. 3. 3. 3. 3. 3. 3. 2. 1.]
 [1. 2. 2. 2. 2. 2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Usiamo Numpy per creare dei dati simulati riferiti ad una situazione reale: in certi casi i dati simulati sono una buona approssimazione della realtà. Nel parco vicino alla scuola è installata una centralina per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta la centralina va in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni dati. Creare un array di 1000 campioni che generino dei valori secondo una distribuzione normale con valore medio 19 e varianza 5 e supporre che la centralina sia andata in errore 20 volte. La distribuzione gaussiana è una buona approssimazione dei dati reali della centralina?

In [14]:
polveri = np.random.normal(19,np.sqrt(5),1000)
numprec = []
for _ in range(20):
    num = np.random.randint(1,1001)
    while num in numprec:               #np.random.choiche(range,num,replace=false) così non estrae due volte lo stesso
        num = np.random.randint(1,1001)
    numprec.append(num)
    polveri[num] = 9999.99
std_polveri = np.std(polveri)
#std_polveri
polveri

array([  15.95689433,   16.84478204,   19.66094388,   17.92265961,
         19.49450896,   20.48842338,   19.84160998,   21.18685217,
         16.71361028,   21.05742302,   22.61534928,   18.16608047,
         15.56383749,   15.90138002,   18.08628498,   19.94347489,
         19.20250746,   13.9273136 ,   18.31190613,   20.55098491,
         17.03543763,   17.94978002,   20.46176399,   22.57953222,
         19.32059156,   24.78843108,   20.17578354,   21.96016858,
         17.18680213,   17.1845704 ,   18.07797675,   25.4616567 ,
         24.29124511,   17.89515629,   17.14826185,   16.58873606,
         17.49293566,   17.26440393,   19.41482902,   19.8394992 ,
         20.66264859,   14.82017075,   19.91069096,   14.95146437,
         21.10901131,   23.34926059,   20.41367587,   18.44743161,
         17.37223685, 9999.99      ,   17.91588933,   20.07233843,
         20.06936603,   17.70017627,   17.8082176 ,   20.46709306,
         18.30507255,   20.65769663,   21.74059908,   25.95676

Creare una funzione che trovi gli elementi comuni a due ndarray monodimensionali di lunghezza diversa.

In [23]:
def trova_comuni(array1, array2):
    lista = []
    if array1.size > array2.size:
        for elemento in array1:
            if elemento in array2:
                lista.append(elemento)
    else:
        for elemento in array2:
            if elemento in array1:
                lista.append(elemento)
    array3 = np.array(lista)
    return array3

arrayA = np.array([1,2,3,4,5,10,9,12])
arrayB = np.array([1,2,7,8,3,10])
print(trova_comuni(arrayA,arrayB))

[ 1  2  3 10]
