In [1]:
import numpy as np

In [12]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))  #concatena due array
a+b #somma elemento per elemento
a*b #moltiplica elemento per elemento
a**2 #eleva elemento per elemento al quadrato


array([ 1,  4,  9, 16], dtype=int32)

In [16]:
a**2+b/3 #funziona anche con operazioni complesse, DEVONO ESSERE LUNGHI UGUALI
a%2 == 0 #buleani

array([False,  True, False,  True])

In [24]:
def isPrime(n):
    for i in range(2,int((np.sqrt(n)+1))):
        if n%i == 0:
            return False
    return True

isPrime(8)

False

In [40]:
c = np.arange(2,30)
c
c**3 #elevamento a potenza universal function
#metodo 1:
for num in c:
    pass
    #print(isPrime(num)) 
#metodo 2:
isPrime_v = np.vectorize(isPrime)   #vettorizza funzione, adesso funziona con gli array, la fa eseguire elemento per elemento
isPrime_v(c)
c[isPrime_v(c)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [3]:
np.ones(shape=(10,10))*8  #moltiplica per 8 elemento per elemento
np.pi      #pi greco
a = np.infty   #infinito
a

inf