In [4]:
import numpy as np
import random
import uuid


In [8]:
a = np.arange(0,12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a+5 #broadcast, perché fa +5 a tutti gli elementi, uno per uno

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [7]:
b=a.reshape((-1,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
c = np.ones(3)*100
c
b+c #broadcast 

array([100., 100., 100.])

In [5]:
n_passeggeri = 2000000
temperature = np.random.normal(36.5,0.25,n_passeggeri)

In [4]:


identificativi = np.array([str(uuid.uuid4()) for _ in range (n_passeggeri)])
for i, t in zip(identificativi, temperature):
    if t > 37.5:
        print(f"passeggero: {i}, di temperatura: {t}")

KeyboardInterrupt: 

In [28]:
print(np.count_nonzero(temperature >37.5)) #conta il numero di passeggeri con temperatura superiore a 37.5

7


In [30]:
print(identificativi[temperature >37.5]) #codice persone con temperatura superiore a 37.5

['143ba697-d612-40cb-9ea9-c7c823ef5599'
 '338c6de6-12b0-412e-b326-bf863aea1edc'
 'ad8ff820-45d3-4d77-81f9-200932448b91'
 'c0a71e5f-0eb9-478f-b55b-25130a6b997e'
 '58ff5523-ae70-4a89-b0af-5fd671a4e58a'
 '236f48e2-f7d9-4358-a5b4-f976ed790b87'
 '5ba48c36-1855-49ba-bd09-62192b2e589d']


In [9]:
%%timeit                                   #comandi magici, 
cont = 0
for t in temperature:
    if t > 37.5:
        print(t)

37.58041360793197
37.507315155151986
37.52616855186319
37.50612794255329
37.50633966350955
37.50469282504036
37.516195029741624
37.55678640255299
37.501992888279965
37.52836812712515
37.5094898948763
37.509977597457635
37.622269724009904
37.63605180621892
37.567380004517894
37.583695267163826
37.55151776982382
37.54837738972473
37.51259395768551
37.6265616764513
37.603468981776786
37.60125149265297
37.515993578113054
37.59917371296072
37.70380464874765
37.517817950420955
37.60284845891572
37.50284437917343
37.536233412255584
37.6655832779636
37.55547436820514
37.517561463843315
37.51272016421389
37.51100094610358
37.55193359180532
37.5069554305403
37.62631916673208
37.51608563902542
37.53719212074328
37.51399902458759
37.56416218327824
37.50283508543643
37.55138488628086
37.505560862004295
37.565860227541975
37.55026674708075
37.52777007665593
37.58522530117404
37.558600643042126
37.50430088583443
37.531650492621885
37.6447989491484
37.53503640288212
37.58890870871242
37.65488798384608

37.54902824505063
37.52028317328062
37.520864773174
37.5306971736352
37.593977940917625
37.565349504249255
37.52535683618985
37.57524955628683
37.51398599088089
37.53554724061423
37.50394678300935
37.60796072604897
37.605347738625014
37.52655171951855
37.75692752997325
37.50608332828139
37.572463082937034
37.51201322689431
37.51304319717732
37.52666099466393
37.571638227671215
37.540281436812926
37.507773553343874
37.5355677906738
37.58838242413402
37.54729538447384
37.521534902417194
37.5012911855263
37.52713493581097
37.781012506386254
37.573500172187856
37.526980167245355
37.53507334427862
37.52588921304812
37.54112706402815
37.52141319487437
37.52407544672257
37.60113409254485
37.51350779316948
37.56766124842316
37.50152171636585
37.505924752425734
37.603735320773126
37.509917897709165
37.57641474331038
37.525442562223674
37.55330050101434
37.534627368004635
37.60338133432764
37.51133366103076
37.602556652108504
37.51117541017865
37.50681965530927
37.54056282879085
37.5021038837858

37.59987619063393
37.78773504312425
37.522104607245076
37.518305630544695
37.51039146305253
37.561866591225666
37.50409701892512
37.520786807061455
37.56172298960294
37.58579497517656
37.55198647909249
37.57978439865671
37.67922072680446
37.51547023081466
37.54431468570341
37.577348463943814
37.58867424526712
37.530458723563804
37.72820188165302
37.529927755670954
37.585396825918465
37.500045477948994
37.577699991558056
37.54369275497371
37.65909976399589
37.62123703133811
37.511465095119284
37.509356464003545
37.52089271265762
37.60390182556013
37.53118438360206
37.51735650553483
37.57477780166942
37.559152507311445
37.622797788784524
37.537748915500195
37.63954342097411
37.51548659500887
37.53299266037808
37.56462586222485
37.535623495947256
37.53039498152164
37.52450930511878
37.52948431435783
37.5584116133661
37.51696771170519
37.540528900751724
37.66480629726908
37.55476714192486
37.59359458723241
37.57437621461727
37.66762151779725
37.52085186136665
37.60015080990327
37.561447997

37.565235198749996
37.596404408491544
37.50210030778517
37.6435278851347
37.52084036572643
37.57480290345563
37.5061234328835
37.5902752702546
37.55454045466976
37.53444535487067
37.58995044645543
37.505891430806464
37.59324436785153
37.50178058033038
37.52651319372501
37.5237024979707
37.697569482438276
37.51061227746615
37.596213739511185
37.51659830192446
37.504442058316144
37.57524930649677
37.54580506080107
37.50683647100473
37.515565975146785
37.52706432557846
37.503898362688496
37.51036968120023
37.529523923141326
37.715623257414265
37.51722894877364
37.54783585087459
37.54392067695727
37.54755655248624
37.53710651399677
37.54098356704958
37.55603307841015
37.523052909825864
37.51374578195125
37.537537132572915
37.58927099579993
37.52545480734388
37.53183879453061
37.53673918164284
37.653383159652115
37.53208314686585
37.54345771743847
37.51764798507085
37.55673751936004
37.53567266697083
37.69892013701288
37.54093100723963
37.50860691817411
37.50006628609516
37.557856311307226


37.5069554305403
37.62631916673208
37.51608563902542
37.53719212074328
37.51399902458759
37.56416218327824
37.50283508543643
37.55138488628086
37.505560862004295
37.565860227541975
37.55026674708075
37.52777007665593
37.58522530117404
37.558600643042126
37.50430088583443
37.531650492621885
37.6447989491484
37.53503640288212
37.58890870871242
37.65488798384608
37.50334612464597
37.53292442370279
37.58871553326946
37.52301530554502
37.56117990382693
37.59651281572168
37.53637428815845
37.565782106805386
37.51539082133568
37.506909965891005
37.5300577433968
37.50782985819309
37.50885234223019
37.72139099913922
37.505482847981064
37.50751134081177
37.54287292487837
37.56417320531783
37.643926382833044
37.519673739895936
37.633050407784104
37.50821834276037
37.650596626957764
37.625211594700616
37.51091041194914
37.6165810485147
37.506073689358495
37.55285065584888
37.530544651148546
37.507213699834
37.61015187798504
37.56807020464784
37.5123705742653
37.538526130888
37.50305970825341
37.50

37.571638227671215
37.540281436812926
37.507773553343874
37.5355677906738
37.58838242413402
37.54729538447384
37.521534902417194
37.5012911855263
37.52713493581097
37.781012506386254
37.573500172187856
37.526980167245355
37.53507334427862
37.52588921304812
37.54112706402815
37.52141319487437
37.52407544672257
37.60113409254485
37.51350779316948
37.56766124842316
37.50152171636585
37.505924752425734
37.603735320773126
37.509917897709165
37.57641474331038
37.525442562223674
37.55330050101434
37.534627368004635
37.60338133432764
37.51133366103076
37.602556652108504
37.51117541017865
37.50681965530927
37.54056282879085
37.502103883785814
37.508381750848926
37.65320908693216
37.55841866046539
37.5094326157593
37.52210773546919
37.50245999155787
37.503965967719544
37.50643379117001
37.541930508048345
37.510309180744265
37.736783284452244
37.65302137251397
37.542741602030155
37.6902010825659
37.51951831194163
37.513592272726854
37.65107075107548
37.54389283002181
37.50895524990562
37.51594083

37.577348463943814
37.58867424526712
37.530458723563804
37.72820188165302
37.529927755670954
37.585396825918465
37.500045477948994
37.577699991558056
37.54369275497371
37.65909976399589
37.62123703133811
37.511465095119284
37.509356464003545
37.52089271265762
37.60390182556013
37.53118438360206
37.51735650553483
37.57477780166942
37.559152507311445
37.622797788784524
37.537748915500195
37.63954342097411
37.51548659500887
37.53299266037808
37.56462586222485
37.535623495947256
37.53039498152164
37.52450930511878
37.52948431435783
37.5584116133661
37.51696771170519
37.540528900751724
37.66480629726908
37.55476714192486
37.59359458723241
37.57437621461727
37.66762151779725
37.52085186136665
37.60015080990327
37.56144799768987
37.78683530013472
37.53594022221624
37.52796287458557
37.65788793173497
37.562320663825254
37.52529982571375
37.61188985579505
37.54447575921421
37.54077867606178
37.54966712026723
37.56714665801063
37.5490042101406
37.667923108824354
37.5028919262558
37.5418043704600

37.52545480734388
37.53183879453061
37.53673918164284
37.653383159652115
37.53208314686585
37.54345771743847
37.51764798507085
37.55673751936004
37.53567266697083
37.69892013701288
37.54093100723963
37.50860691817411
37.50006628609516
37.557856311307226
37.50399475684584
37.51273204709956
37.500788932307586
37.54573739190099
37.523940900548105
37.60745321654887
37.56337165434749
37.55377110586094
37.567921164927355
37.53054958584248
37.54572405562904
37.503074243835925
37.5946914379987
37.571195613109985
37.55444899285663
37.56216292630002
37.64388930698731
37.58670130675558
37.57723928587522
37.505020951659425
37.57362237339095
37.51382724465988
37.58380313212579
37.56623809061699
37.52283533139937
37.54802988762991
37.511249040220136
37.51015119704087
37.56938985007817
37.502293975829474
37.68253642544003
37.69421049697983
37.791073731051604
37.57968766938886
37.64543086874936
37.53812976081933
37.63089723870605
37.51854247434479
37.644995585852996
37.524085460781066
37.7285176861001

37.506909965891005
37.5300577433968
37.50782985819309
37.50885234223019
37.72139099913922
37.505482847981064
37.50751134081177
37.54287292487837
37.56417320531783
37.643926382833044
37.519673739895936
37.633050407784104
37.50821834276037
37.650596626957764
37.625211594700616
37.51091041194914
37.6165810485147
37.506073689358495
37.55285065584888
37.530544651148546
37.507213699834
37.61015187798504
37.56807020464784
37.5123705742653
37.538526130888
37.50305970825341
37.50295838323163
37.504964207703864
37.52674399398556
37.52926181625705
37.53917550004438
37.55880454844259
37.55476034002848
37.5204367336261
37.54970329264314
37.53468052626195
37.528907014290866
37.50818118429734
37.59853675151619
37.588103400087704
37.52096422533072
37.51077320322588
37.508833178233196
37.57318554924412
37.52363639110097
37.601759240809145
37.51362089237713
37.513393154956965
37.637458572621455
37.546401333948495
37.50250286603874
37.558235652293895
37.510174414854745
37.53014659190087
37.53450596957113

37.54112706402815
37.52141319487437
37.52407544672257
37.60113409254485
37.51350779316948
37.56766124842316
37.50152171636585
37.505924752425734
37.603735320773126
37.509917897709165
37.57641474331038
37.525442562223674
37.55330050101434
37.534627368004635
37.60338133432764
37.51133366103076
37.602556652108504
37.51117541017865
37.50681965530927
37.54056282879085
37.502103883785814
37.508381750848926
37.65320908693216
37.55841866046539
37.5094326157593
37.52210773546919
37.50245999155787
37.503965967719544
37.50643379117001
37.541930508048345
37.510309180744265
37.736783284452244
37.65302137251397
37.542741602030155
37.6902010825659
37.51951831194163
37.513592272726854
37.65107075107548
37.54389283002181
37.50895524990562
37.51594083615827
37.59924378102473
37.58822763709027
37.59520953067892
37.533734768312286
37.52014242165242
37.519259539048406
37.67606157211702
37.60801690609986
37.58322022174497
37.58063294809885
37.52536649553345
37.58158913347764
37.50768819139081
37.66968961501

KeyboardInterrupt: 

Un braccio robotico industriale libero di muoversi avanti e indietro
lungo una rotaia è impazzito. Ogni secondo si muove scegliendo a caso
tra due possibili movimenti: 1 cm in avanti, oppure 1 cm indietro. Non è
possibile togliere corrente al robot senza bloccare tutto lo
stabilimento, quindi bisogna attendere lo spegnimento che si effettua
tutti i finesettimana e oggi purtroppo è lunedì! Il nostro responsabile
ci chiede di simulare lo spostamento totale che il robot avrà effettuato
dopo 5 interi giorni di pazzia. Il robot è partito dalla posizione
centrale della rotaia avente coordinata 0cm.


In [45]:
pos_iniziale = 0
for _ in range(432000):
    num = random.randint(0,1)
    if num == 0:
        pos_iniziale += 1
    else:
        pos_iniziale -= 1
print(pos_iniziale)

-380


In [3]:
rand = np.random.choice([-1,1], 432000)
pos = np.cumsum(rand)
pos[-1]

Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno.

In [5]:
alunni = 25
classi = 1000
somma_classi = 0
for _ in range (classi):
    c = np.random.randint(0, 365, alunni)
    
    if len(np.unique(c)) != len(c):
        somma_classi += 1

somma_classi

620

Dato un array monodimensionale di numeri, trovare la posizione di tutti i massimi locali. 
Ad esempio, dato l'array a = [0, 2, 1, 1, 3, 2], 2 e 3 sono massimi locali rispettivamente nelle posizioni 1 e 4.


In [6]:
a = [0, 2, 1, 1, 3, 2]
index = np.argmax(a)

print(f"Indice del val massimo: {index}")
print(f"Val massimo: {a[index]}")

Indice del val massimo: 4
Val massimo: 3


Dato un array monodimensionale di numeri interi compresi tra 0 e 9, generato casualmente, trovare le posizioni dell'array in cui compare la sequenza di numeri [1, 2, 3].


Sul territorio comunale sono installate tre centraline per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta le centraline vanno in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni. Inoltre, per motivi sconosciuti, talvolta le centraline riportano il valore -1. Statisticamente si è visto che il primo errore ha una frequenza dello 0.2% mentre il secondo del 0.1%

Creare una matrice avente 3 colonne e le righe contenente i dati di tutte le centraline registrati nelle 24 ore (si registra il dato ogni minuto)
Eliminare tutte le righe della matrice in cui vi sia almeno una misura errata o una misura di origine sconosciuta

In [7]:
num_minuti = 24*60
due_percento = 0.2/100
uno_percento = 0.1/100

In [32]:
def num_random(a):
    val = np.random.random()
    if val < uno_percento:
        return 9999
    elif val < due_percento:
        return -1
    else:
        return np.random.randint(0,40)
    
num_random_v = np.vectorize(num_random)
matrice = np.ones((num_minuti, 3))
matrice = num_random_v(matrice)


    
    
b_9 = matrice == 9999
b_1 = matrice ==-1
#print(b_9)
#print(b_1)
print(b_9.shape)
print(b_1.shape)
matrice_corretta = matrice[np.invert(b_9+b_1)]
matrice_corretta
#print(list(matrice[np.invert(b_9+b_1)]))
g = np.logical_or(b_1,b_9)
g.shape

(1440, 3)
(1440, 3)


(1440, 3)

In [36]:
np.count_nonzero(g)
matrice[4]
g[4]
np.sum(g[4])

0