In [3]:
import numpy as np

In [4]:
lista = [1,2,3,4,5]
lista_array = np.array(lista) #per passare da lista ad array usi il costruttore 
lista
np.array?

In [8]:
lista_array #non è una lista, è un array numpy
#anche per python sono oggetti diversi

array([1, 2, 3, 4, 5])

In [16]:
#np.zeros?per ottenere la documentazione sul metodo 
np.zeros(10, dtype=int) #array lungo 10 di tipo float di default, se lo specifichi diventa il tipo che dici


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((5,10), dtype=float) #matrice di 0, np.ones = array di 1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,1)) #le ia imparano con dati a molte dimensioni, per es nella tesla tutto ciò che riceve finisce in una matrice 

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [20]:
np.random.uniform() #numeri che si comportano come casuali, ma generati da un altgorimo deterministico, anche se 
                  #apparentemente sembrano casuali
                  #calculus, libreria che serve per calcolare derivate e integrali

0.8569162651774506

In [21]:
np.random.uniform(size = 100) #array di 100 numeri casuali, sempre numeri float

array([0.35094597, 0.74785007, 0.96829644, 0.17498868, 0.94792009,
       0.60633884, 0.10628291, 0.65857833, 0.02322332, 0.48440902,
       0.06570516, 0.38895663, 0.78122985, 0.1832536 , 0.02889259,
       0.38782525, 0.96248079, 0.26283855, 0.5754329 , 0.65696788,
       0.37561871, 0.36378417, 0.65131242, 0.81447668, 0.84391954,
       0.0854793 , 0.4529255 , 0.8739773 , 0.54515697, 0.81473057,
       0.15335993, 0.17765994, 0.44354607, 0.14687513, 0.62104104,
       0.30431128, 0.62984414, 0.09618287, 0.03813485, 0.00902936,
       0.17681993, 0.07404525, 0.34007986, 0.46405737, 0.42364421,
       0.4222768 , 0.30735402, 0.3820726 , 0.90988883, 0.42274221,
       0.6007316 , 0.62879596, 0.16679534, 0.09313881, 0.55560003,
       0.59928566, 0.99680235, 0.4802743 , 0.63750279, 0.27644016,
       0.21627828, 0.47686986, 0.26217962, 0.40952853, 0.30318387,
       0.75295645, 0.75142419, 0.44992448, 0.62261093, 0.83633594,
       0.71450905, 0.94298158, 0.63508658, 0.89897069, 0.66566

In [22]:
np.random.normal(size = 100) #distribuzione gaussiana

array([ 0.45465084, -0.4343987 , -0.16865333,  0.0952317 ,  0.67315261,
        1.07132599,  0.91445086,  1.1003923 ,  1.13064605,  0.41708361,
       -0.05013066, -0.24636899, -0.55183006, -0.14513691,  0.56850739,
        1.75063998,  0.44126113,  0.46505008,  1.02077063,  0.87223767,
        0.53617727, -0.14366229,  1.07583353, -0.81910205, -0.18453398,
        0.61428438,  0.40381417,  0.76679608, -0.58283411, -0.26529388,
        0.41176556, -0.09739743,  0.71271655,  1.31435083,  0.20859443,
        0.02953095,  0.31023644,  0.50771828, -0.34830732, -0.36346554,
        0.50580702, -0.64796809, -0.5337129 , -1.75603849,  1.28035161,
       -1.12818773,  0.40094812,  3.35075584,  0.0796821 , -1.4811105 ,
        0.76872604,  0.46650817,  0.15164911,  0.5310634 ,  1.61528849,
        1.07548892,  0.38602054, -1.50548209, -0.01365035, -0.46503026,
       -0.81781821, -0.05335077, -1.13189166,  1.15051601,  1.08784645,
       -1.19130771,  1.84171607,  0.42834362,  1.11735089, -1.95

In [5]:
np.random.normal(loc = 5, scale = 1, size = 100)
np.random.normal?

In [30]:
np.random.random_integers(low=1,high=6,size=10) #simula lanci del dado, high è compreso, pure low, e sono distribuiti
                                                #in maniera uniforme

<ipython-input-30-7ffa12105ea3>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  np.random.random_integers(low=1,high=6,size=10)


array([4, 2, 6, 4, 5, 1, 5, 3, 2, 3])

In [49]:
np.random.choice(["testa", "croce"]) #estrae a caso un elemento da una lista, con size = 10 crea array con 10 elementi tirati a caso

'testa'

In [50]:
#le diverse dimensioni degli array hanno un nome o nunìmero che è standard.
#1d = asse 0
#2d = asse 0 verticale(righe), asse 1 orizzontale(colonna)


In [55]:
matrice = np.random.uniform(size=(4,5))
print(matrice) #4 righe 5 colonne

[[0.68136828 0.6689506  0.79058944 0.63443128 0.19410437]
 [0.30233347 0.94012666 0.64083459 0.65547519 0.78369735]
 [0.76598593 0.06683784 0.82847248 0.19723207 0.31091609]
 [0.74568717 0.46684819 0.2842751  0.02032055 0.08102263]]


In [58]:
np.shape(matrice) #ritorna una tupla con numero righe e colonne
np.size(matrice)  #ritorna al numero di elementi dell'array

20

In [61]:
vettore = np.array([1,2,3,4,5])
print(np.shape(vettore))
print(np.size(vettore))

(5,)
5


In [64]:
matrice1 = np.ravel(matrice) #permette di trasformare matrici in array, concatenando il tutto
matrice1 

array([0.68136828, 0.6689506 , 0.79058944, 0.63443128, 0.19410437,
       0.30233347, 0.94012666, 0.64083459, 0.65547519, 0.78369735,
       0.76598593, 0.06683784, 0.82847248, 0.19723207, 0.31091609,
       0.74568717, 0.46684819, 0.2842751 , 0.02032055, 0.08102263])

In [65]:
vettore[2] #0,1,2,3,4 -> indici

3

In [67]:
print(matrice[2]) #stampa la terza riga
print(matrice[2][3]) #dstampa il 4 valore della 3 riga

[0.76598593 0.06683784 0.82847248 0.19723207 0.31091609]
0.19723206917452218


In [68]:
matrice[0] = 1111.1
print(matrice1) #sia matrice che matrice1 puntano alla stessa cella, quindi se modifichi matrice verrà modificata pure matrice1, pure se modifichi matrice1 cambia matrice

[1.11110000e+03 1.11110000e+03 1.11110000e+03 1.11110000e+03
 1.11110000e+03 3.02333475e-01 9.40126658e-01 6.40834587e-01
 6.55475187e-01 7.83697348e-01 7.65985932e-01 6.68378447e-02
 8.28472483e-01 1.97232069e-01 3.10916091e-01 7.45687168e-01
 4.66848191e-01 2.84275099e-01 2.03205508e-02 8.10226266e-02]


In [74]:
matrice.reshape(20,1)#ritorna un array con gli stessi dati, ma con la nuova forma passata, a patto che sia compatibile

array([[1.11110000e+03],
       [1.11110000e+03],
       [1.11110000e+03],
       [1.11110000e+03],
       [1.11110000e+03],
       [3.02333475e-01],
       [9.40126658e-01],
       [6.40834587e-01],
       [6.55475187e-01],
       [7.83697348e-01],
       [7.65985932e-01],
       [6.68378447e-02],
       [8.28472483e-01],
       [1.97232069e-01],
       [3.10916091e-01],
       [7.45687168e-01],
       [4.66848191e-01],
       [2.84275099e-01],
       [2.03205508e-02],
       [8.10226266e-02]])

In [75]:
#matrice trasposta: scambia righe e colonne
np.transpose(matrice) #inverte righe e colonne di una matrice

array([[1.11110000e+03, 3.02333475e-01, 7.65985932e-01, 7.45687168e-01],
       [1.11110000e+03, 9.40126658e-01, 6.68378447e-02, 4.66848191e-01],
       [1.11110000e+03, 6.40834587e-01, 8.28472483e-01, 2.84275099e-01],
       [1.11110000e+03, 6.55475187e-01, 1.97232069e-01, 2.03205508e-02],
       [1.11110000e+03, 7.83697348e-01, 3.10916091e-01, 8.10226266e-02]])

In [3]:
#persona che lancia un dato a 6 facce, calcolare la % di 10000 lanci per quante volte esce il 6
lanci_dado = np.random.randint(1,7,10000)
lanci_dado1 = np.random.randint(1,7,10000)
lanci_dado == 6 #da in output un array di buleani con true se è 6, false se è diverso
np.count_nonzero(lanci_dado == 6)#conta gli elementi non nulli count_nonzero, mentre con == 6 conta solo i 6 (1/6)

array([5, 4, 5, ..., 5, 4, 5])

In [144]:
np.count_nonzero(lanci_dado >= 4) /10000

0.509

In [150]:
lanci_dado + lanci_dado1 == 8
print(np.count_nonzero(lanci_dado + lanci_dado1 == 8) /10000)
print(np.count_nonzero(lanci_dado + lanci_dado1 >= 6) /10000)  #somma gli array elemento per elemento gli array di lunghezza uguale

0.1373
0.7176
