In [112]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6])


In [16]:
a[...] = 5   #assegna 5 a tutti gli elementi dell'array
a

array([5, 5, 5, 5, 5, 5])

In [21]:
b = a[2:5]
b[...] = 99   #b punta ad a, quindi modificato b viene modificato a, b è una view di a
a

array([ 5,  5, 99, 99, 99,  5])

In [23]:
b.base is a #per vedere se b è linkato ad a

True

In [30]:
c = a
c.base is a


False

## FANCY INDEXING
quando si usa l'indicizzazione fancy si creano coppie 

In [32]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [39]:
b = a[[True,False,True,False,True,False]]
b.base is a

False

## esempio

In [46]:
dadoAlice = np.random.randint(1,7,10)
dadoBob = np.random.randint(1,7,10)
print(dadoAlice)
print(dadoBob)

[5 3 6 4 6 1 3 5 5 2]
[3 2 6 5 2 6 4 5 6 2]


In [52]:
dado_vittorie_alice = dadoalice[dadoAlice > dadoBob]   #alice> bob è array di buleni, indicizzando il dadoalice trovi i numeri vincenti
dado_vittorie_alice.base is dadoAlice    #dado_vittorie_alice è una copia

False

In [56]:
a = np.array([1,2,3,4,5,6])
b = a[[2,4,5]]  #invertendo l'ordine ti da i numeri al contrario, molto utile
b

array([3, 5, 6])

In [73]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[2][1])
print(mat[:,2]) #ottieni terza colonna
terza_colonna = mat[:,2]
terza_colonna[...] = 11  #così crei una view, non copia
print(mat)

8
[3 6 9]
[[ 1  2 11]
 [ 4  5 11]
 [ 7  8 11]]


In [79]:
mat2 = np.random.randint(0,2,size=(10,10))
mat2

array([[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 0, 0, 0]])

In [111]:
mat2[:,0] = np.random.randint(0,100,10)
mat2[:,9] = np.random.randint(0,100,10)
mat2[0,:] = np.random.randint(0,100,10)
mat2[9,:] = np.random.randint(0,100,10)
mat2

array([[19, 52, 89, 77, 99, 19, 69, 47, 80,  2],
       [48,  0,  0,  1,  1,  0,  0,  0,  0, 59],
       [81,  0,  1,  1,  0,  1,  0,  1,  1, 28],
       [ 6,  0,  1,  1,  1,  1,  0,  0,  0, 48],
       [ 6,  0,  1,  1,  1,  1,  0,  0,  0, 22],
       [67,  0,  1,  1,  1,  0,  1,  1,  0, 98],
       [95,  0,  0,  0,  1,  1,  0,  0,  0, 52],
       [38,  0,  1,  0,  0,  0,  1,  1,  1, 33],
       [94,  0,  0,  0,  1,  0,  1,  0,  1, 30],
       [88, 55, 54, 89, 92, 65, 55, 50, 44, 79]])